fastapi:
  base-url: http://163.239.27.110:8890

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /index.html
#    groups-order: DESC
#    doc-expansion: none
#    tags-sorter: alpha
#    operationsSorter: method
#    disable-swagger-default-url: true
    display-request-duration: true
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
logging:
  file:
    name: app.log
  level:
    org.springframework: INFO
    org.springframework.boot.web.servlet.error: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      stack:
        auto: false
      region:
        static: ap-southeast-2
      s3:
        endpoint: https://kr.object.ncloudstorage.com
        bucket: impossible.bucket

  application:
    name: demo
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e954bc827d2ea8fa11a15b0286fc682e
            client-secret: E8be7qDJI4hGUy3VARLdomQotKY7gwx7
            client-name: Kakao
            provider: kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-authentication-method: client_secret_post

          apple:
            client-id: com.dancewithgnu.impossible
#            client-secret: "{jwt.token}"
            client-name: Apple
            provider: apple
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: "https://49b0-163-239-255-151.ngrok-free.app/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            scope: name, email
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: name
